export const GOLF_DAD_JOKES: { setup: string; punchline: string }[] = [
  { setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one." },
  { setup: "What's a golfer's favorite letter?", punchline: "Tee." },
  { setup: "Why do golfers always carry an extra pair of socks?", punchline: "In case they get a hole in one." },
  { setup: "What are a golfer's favorite flowers?", punchline: "Fore-get-me-nots." },
  { setup: "Why did the golfer wear two pairs of pants?", punchline: "In case he got a hole in one. Wait... I already said that one. Mulligan!" },
  { setup: "What's the difference between a golfer and a fisherman?", punchline: "When a golfer lies, he doesn't have to bring anything home to prove it." },
  { setup: "Why do golfers hate cake?", punchline: "Because they might get a slice." },
  { setup: "What did the golf ball say to the other golf ball?", punchline: "See you around." },
  { setup: "Why is golf like taxes?", punchline: "You drive hard to get to the green, and then end up in the hole." },
  { setup: "What's a golfer's worst nightmare?", punchline: "The Bogeyman." },
  { setup: "Why did the golfer bring a ladder?", punchline: "He wanted to reach the high scores." },
  { setup: "What do you call a monkey who wins the Masters?", punchline: "The Chimp-ion." },
  { setup: "Why are golf balls like eggs?", punchline: "They're white, sold by the dozen, and a week later you have to go out and buy more." },
  { setup: "What does a golfer do on his day off?", punchline: "Putts around the house." },
  { setup: "Why did the golfer bring string to the course?", punchline: "So he could tie the score." },
  { setup: "What's the easiest shot in golf?", punchline: "Your fourth putt." },
  { setup: "Why did the golfer get new shoes?", punchline: "Because his old ones had a hole in one." },
  { setup: "What do golfers do when they retire?", punchline: "They just putter around." },
  { setup: "What did the golfer name his son?", punchline: "Chip." },
  { setup: "Why should you never golf in the jungle?", punchline: "Too many cheetahs." },
  { setup: "What do you call a wizard who plays golf?", punchline: "Harry Putter." },
  { setup: "Why was Cinderella so bad at golf?", punchline: "Her coach was a pumpkin." },
  { setup: "What's the difference between a bad golfer and a bad skydiver?", punchline: "A bad golfer goes WHACK... 'dang.' A bad skydiver goes 'dang'... WHACK." },
  { setup: "Why did the golfer bring birdseed?", punchline: "He was hoping for a birdie." },
  { setup: "What do you call a lion on the golf course?", punchline: "Roarin' on the back nine." },
  { setup: "Why was the golf course so quiet?", punchline: "Because everyone was afraid to drive." },
  { setup: "What's a golfer's favorite type of music?", punchline: "Swing." },
  { setup: "Why did the golfer cry?", punchline: "He was going through a rough patch." },
  { setup: "What do you call four golfers in a thunderstorm?", punchline: "Tee time for lightning." },
  { setup: "Why did the golfer bring an umbrella?", punchline: "In case of a rain delay. Just kidding, he played through it." },
  { setup: "What's a golfer's favorite dance?", punchline: "The bogey." },
  { setup: "Why did the golfer's wife leave him?", punchline: "He spent too much time in his sand trap." },
  { setup: "What do you call a really fast golfer?", punchline: "A speed wedge." },
  { setup: "How do golfers stay cool?", punchline: "They stand near the fans." },
  { setup: "Why did the golfer get glasses?", punchline: "To improve his driving vision." },
  { setup: "What's a golfer's favorite bird?", punchline: "An eagle. But they'd settle for a birdie." },
  { setup: "Why did the golf club go to therapy?", punchline: "It had too many issues with its shaft." },
  { setup: "What do you get when you cross a golfer and a donut?", punchline: "A hole in one." },
  { setup: "Why don't golfers ever get lonely?", punchline: "Because they always have their irons in the fire." },
  { setup: "What do you call a golfer's autobiography?", punchline: "A fairway tale." },
  { setup: "Why did the golfer bring a pencil to bed?", punchline: "To draw his dreams under par." },
  { setup: "What did the ocean say to the golfer?", punchline: "Nothing. It just waved." },
  { setup: "Why did the golfer go to the bank?", punchline: "To check his balance on the green." },
  { setup: "What do you call a bear on the golf course?", punchline: "A bogey bear." },
  { setup: "Why did the golfer wear armor?", punchline: "He was playing a knight round." },
  { setup: "What do golfers and plumbers have in common?", punchline: "They both hate a bad pipe." },
  { setup: "Why did the golfer stare at his orange juice?", punchline: "Because it said 'concentrate.'" },
  { setup: "What's a golfer's least favorite meal?", punchline: "A club sandwich. Too many memories." },
  { setup: "Why did the golfer jump in the lake?", punchline: "He wanted to make a splash on the leaderboard." },
  { setup: "What do you say to a golfer who just got dumped?", punchline: "Hey, at least you can play more golf now." },
  { setup: "Why do retired golfers make great detectives?", punchline: "They're used to following through." },
  { setup: "What did the caddie say to the terrible golfer?", punchline: "'Nice practice swing. Are you gonna hit it now?'" },
  { setup: "Why is it hard to drive in golf?", punchline: "Because the ball doesn't have a steering wheel." },
  { setup: "What did the tee say to the golf ball?", punchline: "'I'm under a lot of pressure here.'" },
  { setup: "Why don't golfers eat breakfast?", punchline: "They already had a tee." },
  { setup: "What's a golfer's favorite day of the week?", punchline: "Wedge-nesday." },
  { setup: "What did the golfer say after losing all his balls?", punchline: "'This is driving me nuts.'" },
  { setup: "Why are computers so good at golf?", punchline: "Because they have hard drives." },
  { setup: "What do golfers use in the rain?", punchline: "A pitch-fork." },
  { setup: "What did one golf ball say to the other?", punchline: "'I'm teed off!'" },
  { setup: "Why did the golfer bring 18 shirts?", punchline: "One for each hole." },
  { setup: "What's a golfer's spirit animal?", punchline: "The birdie. Unless it's a bad day, then the bogeyman." },
  { setup: "Why is golf like filing your taxes?", punchline: "You drive hard, end up in a trap, and wish you'd stayed home." },
  { setup: "What do you call a dinosaur who plays golf?", punchline: "A Tee-Rex." },
  { setup: "Why did the golfer bring a tiny pencil?", punchline: "To keep his short game sharp." },
]

export function getDailyJoke(): { setup: string; punchline: string; jokeNumber: number } {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const diff = now.getTime() - start.getTime()
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  const index = dayOfYear % GOLF_DAD_JOKES.length
  return { ...GOLF_DAD_JOKES[index], jokeNumber: index + 1 }
}
